"""Model registry used by Alembic and tests."""

from book_engine.catalog.models import Author, Edition, Identifier, Work, WorkAuthor
from book_engine.discovery.models import (
    DiscoveryCandidate,
    DiscoveryQuery,
    DiscoveryRun,
)
from book_engine.enrichment.models import (
    Concept,
    CoverCandidate,
    EnrichmentAttempt,
    EnrichmentRun,
    MetadataClaim,
    MetadataMatch,
    ProviderResponse,
    Series,
    WorkConceptClaim,
    WorkSeriesClaim,
)
from book_engine.importing.models import ImportRecord, ImportRun
from book_engine.library.models import (
    LibraryEntry,
    LibraryEntryShelf,
    ReadingEvent,
    Shelf,
)
from book_engine.recommendations.models import (
    DerivationRun,
    RecommendationExplanation,
    RecommendationFeedback,
    RecommendationItem,
    RecommendationNeighbor,
    RecommendationRun,
    RecommendationSignal,
    TasteProfileRun,
    TasteProfileValue,
    TraitDefinition,
    WorkEmbedding,
    WorkRepresentation,
    WorkTraitValue,
)
from book_engine.web.models import BrowseFacet, ConceptFacetMapping

__all__ = [
    "Author",
    "Concept",
    "CoverCandidate",
    "Edition",
    "DiscoveryCandidate",
    "DiscoveryQuery",
    "DiscoveryRun",
    "EnrichmentAttempt",
    "EnrichmentRun",
    "Identifier",
    "ImportRecord",
    "ImportRun",
    "LibraryEntry",
    "LibraryEntryShelf",
    "MetadataClaim",
    "MetadataMatch",
    "ProviderResponse",
    "ReadingEvent",
    "Shelf",
    "Series",
    "Work",
    "WorkAuthor",
    "WorkConceptClaim",
    "WorkSeriesClaim",
    "BrowseFacet",
    "ConceptFacetMapping",
    "DerivationRun",
    "RecommendationExplanation",
    "RecommendationFeedback",
    "RecommendationItem",
    "RecommendationNeighbor",
    "RecommendationRun",
    "RecommendationSignal",
    "TasteProfileRun",
    "TasteProfileValue",
    "TraitDefinition",
    "WorkEmbedding",
    "WorkRepresentation",
    "WorkTraitValue",
]
