"""create initial catalog schema

Revision ID: 01ddce26335e
Revises:
Create Date: 2026-08-20 21:46:48.259295
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "01ddce26335e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("sort_name", sa.String(length=300), nullable=True),
        sa.Column("external_key", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("external_key", name=op.f("uq_authors_external_key")),
    )
    with op.batch_alter_table("authors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_authors_sort_name"), ["sort_name"], unique=False
        )

    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_filename", sa.String(length=500), nullable=False),
        sa.Column("file_checksum", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("created_rows", sa.Integer(), nullable=False),
        sa.Column("updated_rows", sa.Integer(), nullable=False),
        sa.Column("unchanged_rows", sa.Integer(), nullable=False),
        sa.Column("ambiguous_rows", sa.Integer(), nullable=False),
        sa.Column("failed_rows", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'completed_with_errors', 'failed')",
            name=op.f("ck_import_runs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_runs")),
    )
    op.create_table(
        "shelves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shelves")),
        sa.UniqueConstraint("name", name=op.f("uq_shelves_name")),
    )
    op.create_table(
        "works",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("subtitle", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("original_publication_year", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("fiction_status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fiction_status IN ('fiction', 'nonfiction', 'mixed', 'unknown')",
            name=op.f("ck_works_fiction_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_works")),
    )
    op.create_table(
        "editions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("format", sa.String(length=100), nullable=True),
        sa.Column("publisher", sa.String(length=300), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("cover_url", sa.String(length=2000), nullable=True),
        sa.Column("cover_source", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_editions_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_editions")),
    )
    op.create_table(
        "library_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("personal_rating", sa.Integer(), nullable=True),
        sa.Column("personal_notes", sa.String(), nullable=True),
        sa.Column("first_read_on", sa.Date(), nullable=True),
        sa.Column("last_read_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('read', 'reading', 'want_to_read', 'saved_recommendation', 'rejected')",
            name=op.f("ck_library_entries_status"),
        ),
        sa.CheckConstraint(
            "personal_rating IS NULL OR personal_rating BETWEEN 1 AND 5",
            name=op.f("ck_library_entries_personal_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_library_entries_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library_entries")),
        sa.UniqueConstraint("work_id", name=op.f("uq_library_entries_work_id")),
    )
    op.create_table(
        "work_authors",
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
            name=op.f("fk_work_authors_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_work_authors_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "work_id", "author_id", "role", name=op.f("pk_work_authors")
        ),
    )
    op.create_table(
        "identifiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=True),
        sa.Column("edition_id", sa.Integer(), nullable=True),
        sa.Column("scheme", sa.String(length=50), nullable=False),
        sa.Column("value", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(work_id IS NOT NULL AND edition_id IS NULL) OR (work_id IS NULL AND edition_id IS NOT NULL)",
            name=op.f("ck_identifiers_exactly_one_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_identifiers_edition_id_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_identifiers_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identifiers")),
        sa.UniqueConstraint("scheme", "value", name=op.f("uq_identifiers_scheme")),
    )
    op.create_table(
        "import_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_run_id", sa.Integer(), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=False),
        sa.Column("source_record_key", sa.String(length=300), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("raw_payload_checksum", sa.String(length=64), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=True),
        sa.Column("edition_id", sa.Integer(), nullable=True),
        sa.Column("resolution_status", sa.String(length=32), nullable=False),
        sa.Column("resolution_notes", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "resolution_status IN ('pending', 'created', 'matched', 'updated', 'unchanged', 'ambiguous', 'failed')",
            name=op.f("ck_import_records_resolution_status"),
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_import_records_edition_id_editions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_runs.id"],
            name=op.f("fk_import_records_import_run_id_import_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_import_records_work_id_works"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_records")),
        sa.UniqueConstraint(
            "import_run_id",
            "source_row_number",
            name=op.f("uq_import_records_import_run_id"),
        ),
    )
    op.create_table(
        "library_entry_shelves",
        sa.Column("library_entry_id", sa.Integer(), nullable=False),
        sa.Column("shelf_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_entry_id"],
            ["library_entries.id"],
            name=op.f("fk_library_entry_shelves_library_entry_id_library_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shelf_id"],
            ["shelves.id"],
            name=op.f("fk_library_entry_shelves_shelf_id_shelves"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "library_entry_id", "shelf_id", name=op.f("pk_library_entry_shelves")
        ),
    )
    op.create_table(
        "reading_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_entry_id", sa.Integer(), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=True),
        sa.Column("finished_on", sa.Date(), nullable=True),
        sa.Column("date_precision", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "date_precision IN ('day', 'month', 'year', 'unknown')",
            name=op.f("ck_reading_events_date_precision"),
        ),
        sa.ForeignKeyConstraint(
            ["library_entry_id"],
            ["library_entries.id"],
            name=op.f("fk_reading_events_library_entry_id_library_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_events")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reading_events")
    op.drop_table("library_entry_shelves")
    op.drop_table("import_records")
    op.drop_table("identifiers")
    op.drop_table("work_authors")
    op.drop_table("library_entries")
    op.drop_table("editions")
    op.drop_table("works")
    op.drop_table("shelves")
    op.drop_table("import_runs")
    with op.batch_alter_table("authors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_authors_sort_name"))

    op.drop_table("authors")
    # ### end Alembic commands ###
