"""add metadata enrichment provenance

Revision ID: 89793769d1c7
Revises: 4c2355285e99
Create Date: 2026-08-21 09:10:00.381607
"""

from collections.abc import Sequence
from datetime import datetime

import sqlalchemy as sa
from alembic import op

revision: str = "89793769d1c7"
down_revision: str | Sequence[str] | None = "4c2355285e99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("normalized_label", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concepts")),
        sa.UniqueConstraint("kind", "normalized_label", name=op.f("uq_concepts_kind")),
    )
    op.create_table(
        "enrichment_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("succeeded_count", sa.Integer(), nullable=False),
        sa.Column("missed_count", sa.Integer(), nullable=False),
        sa.Column("ambiguous_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'completed_with_errors', 'failed')",
            name=op.f("ck_enrichment_runs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrichment_runs")),
    )
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_series_normalized_name")),
    )
    op.create_table(
        "enrichment_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("lookup_strategy", sa.String(length=50), nullable=False),
        sa.Column("lookup_key", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("match_method", sa.String(length=50), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("decision_reason", sa.String(), nullable=True),
        sa.Column("candidate_summary", sa.JSON(), nullable=False),
        sa.Column("error_type", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'missed', 'ambiguous', 'failed', 'skipped_cached')",
            name=op.f("ck_enrichment_attempts_status"),
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_enrichment_attempts_edition_id_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["enrichment_runs.id"],
            name=op.f("fk_enrichment_attempts_run_id_enrichment_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_enrichment_attempts_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrichment_attempts")),
    )
    op.create_table(
        "provider_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("request_key", sa.String(length=1000), nullable=False),
        sa.Column("endpoint", sa.String(length=500), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("payload_checksum", sa.String(length=64), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["enrichment_attempts.id"],
            name=op.f("fk_provider_responses_attempt_id_enrichment_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_responses")),
    )
    with op.batch_alter_table("provider_responses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provider_responses_request_key"),
            ["request_key"],
            unique=False,
        )

    op.create_table(
        "cover_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("provider_response_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("external_cover_id", sa.String(length=300), nullable=False),
        sa.Column("small_url", sa.String(length=2000), nullable=True),
        sa.Column("medium_url", sa.String(length=2000), nullable=True),
        sa.Column("large_url", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_cover_candidates_edition_id_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_response_id"],
            ["provider_responses.id"],
            name=op.f("fk_cover_candidates_provider_response_id_provider_responses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cover_candidates")),
        sa.UniqueConstraint(
            "edition_id",
            "provider",
            "external_cover_id",
            name=op.f("uq_cover_candidates_edition_id"),
        ),
    )
    op.create_table(
        "metadata_claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=True),
        sa.Column("edition_id", sa.Integer(), nullable=True),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("normalized_value", sa.String(length=1000), nullable=True),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("import_record_id", sa.Integer(), nullable=True),
        sa.Column("provider_response_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("selection_reason", sa.String(), nullable=True),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind IN ('goodreads_import', 'provider', 'manual')",
            name=op.f("ck_metadata_claims_source_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('accepted', 'candidate', 'rejected', 'superseded')",
            name=op.f("ck_metadata_claims_status"),
        ),
        sa.CheckConstraint(
            "(work_id IS NOT NULL AND edition_id IS NULL) OR (work_id IS NULL AND edition_id IS NOT NULL)",
            name=op.f("ck_metadata_claims_exactly_one_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_metadata_claims_edition_id_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["import_record_id"],
            ["import_records.id"],
            name=op.f("fk_metadata_claims_import_record_id_import_records"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_response_id"],
            ["provider_responses.id"],
            name=op.f("fk_metadata_claims_provider_response_id_provider_responses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_metadata_claims_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metadata_claims")),
    )
    with op.batch_alter_table("metadata_claims", schema=None) as batch_op:
        batch_op.create_index(
            "uq_metadata_claims_accepted_edition_field",
            ["edition_id", "field_name"],
            unique=True,
            sqlite_where=sa.text("status = 'accepted' AND edition_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_metadata_claims_accepted_work_field",
            ["work_id", "field_name"],
            unique=True,
            sqlite_where=sa.text("status = 'accepted' AND work_id IS NOT NULL"),
        )

    op.create_table(
        "metadata_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("provider_response_id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("edition_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("external_work_id", sa.String(length=300), nullable=True),
        sa.Column("external_edition_id", sa.String(length=300), nullable=True),
        sa.Column("match_method", sa.String(length=50), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('accepted', 'ambiguous', 'rejected')",
            name=op.f("ck_metadata_matches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["enrichment_attempts.id"],
            name=op.f("fk_metadata_matches_attempt_id_enrichment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["edition_id"],
            ["editions.id"],
            name=op.f("fk_metadata_matches_edition_id_editions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_response_id"],
            ["provider_responses.id"],
            name=op.f("fk_metadata_matches_provider_response_id_provider_responses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_metadata_matches_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metadata_matches")),
    )
    op.create_table(
        "work_concept_claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("provider_response_id", sa.Integer(), nullable=False),
        sa.Column("original_label", sa.String(length=500), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_work_concept_claims_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_response_id"],
            ["provider_responses.id"],
            name=op.f("fk_work_concept_claims_provider_response_id_provider_responses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_work_concept_claims_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_concept_claims")),
        sa.UniqueConstraint(
            "work_id",
            "concept_id",
            "provider_response_id",
            name=op.f("uq_work_concept_claims_work_id"),
        ),
    )
    op.create_table(
        "work_series_claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("provider_response_id", sa.Integer(), nullable=False),
        sa.Column("sequence_label", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_response_id"],
            ["provider_responses.id"],
            name=op.f("fk_work_series_claims_provider_response_id_provider_responses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
            name=op.f("fk_work_series_claims_series_id_series"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["works.id"],
            name=op.f("fk_work_series_claims_work_id_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_series_claims")),
        sa.UniqueConstraint(
            "work_id",
            "series_id",
            "provider_response_id",
            name=op.f("uq_work_series_claims_work_id"),
        ),
    )
    with op.batch_alter_table("identifiers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("import_record_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("provider_response_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_identifiers_provider_response_id_provider_responses"),
            "provider_responses",
            ["provider_response_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_identifiers_import_record_id_import_records"),
            "import_records",
            ["import_record_id"],
            ["id"],
            ondelete="SET NULL",
        )

    _backfill_goodreads_provenance()

    # ### end Alembic commands ###


def _backfill_goodreads_provenance() -> None:
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE identifiers
            SET import_record_id = COALESCE(
                (
                    SELECT MIN(import_records.id)
                    FROM import_records
                    WHERE import_records.edition_id = identifiers.edition_id
                ),
                (
                    SELECT MIN(import_records.id)
                    FROM import_records
                    WHERE import_records.work_id = identifiers.work_id
                )
            )
            WHERE source = 'goodreads_csv'
            """
        )
    )

    claims = sa.table(
        "metadata_claims",
        sa.column("work_id", sa.Integer()),
        sa.column("edition_id", sa.Integer()),
        sa.column("field_name", sa.String()),
        sa.column("value_json", sa.JSON()),
        sa.column("normalized_value", sa.String()),
        sa.column("source_kind", sa.String()),
        sa.column("import_record_id", sa.Integer()),
        sa.column("provider_response_id", sa.Integer()),
        sa.column("provider", sa.String()),
        sa.column("confidence", sa.Float()),
        sa.column("status", sa.String()),
        sa.column("selection_reason", sa.String()),
        sa.column("observed_at", sa.DateTime()),
    )
    rows = connection.execute(
        sa.text(
            """
            SELECT
                works.id AS work_id,
                editions.id AS edition_id,
                works.title AS work_title,
                works.original_publication_year,
                editions.title AS edition_title,
                editions.format,
                editions.publisher,
                editions.publication_date,
                editions.publication_year,
                editions.page_count,
                editions.language,
                source.id AS import_record_id,
                source.created_at AS observed_at
            FROM works
            JOIN editions ON editions.work_id = works.id
            JOIN import_records AS source ON source.id = (
                SELECT MIN(candidate.id)
                FROM import_records AS candidate
                WHERE candidate.work_id = works.id
                  AND candidate.resolution_status IN (
                    'created', 'matched', 'updated', 'unchanged'
                  )
            )
            """
        )
    ).mappings()
    claim_rows: list[dict[str, object]] = []
    for row in rows:
        for owner, field_name, value in (
            ("work", "title", row["work_title"]),
            (
                "work",
                "original_publication_year",
                row["original_publication_year"],
            ),
            ("edition", "title", row["edition_title"]),
            ("edition", "format", row["format"]),
            ("edition", "publisher", row["publisher"]),
            ("edition", "publication_date", row["publication_date"]),
            ("edition", "publication_year", row["publication_year"]),
            ("edition", "page_count", row["page_count"]),
            ("edition", "language", row["language"]),
        ):
            if value is None:
                continue
            claim_rows.append(
                {
                    "work_id": row["work_id"] if owner == "work" else None,
                    "edition_id": row["edition_id"] if owner == "edition" else None,
                    "field_name": field_name,
                    "value_json": value,
                    "normalized_value": str(value).casefold(),
                    "source_kind": "goodreads_import",
                    "import_record_id": row["import_record_id"],
                    "provider_response_id": None,
                    "provider": "goodreads_csv",
                    "confidence": 1.0,
                    "status": "accepted",
                    "selection_reason": "Canonical value imported from Goodreads",
                    "observed_at": (
                        datetime.fromisoformat(row["observed_at"])
                        if isinstance(row["observed_at"], str)
                        else row["observed_at"]
                    ),
                }
            )
    if claim_rows:
        connection.execute(claims.insert(), claim_rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("identifiers", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_identifiers_import_record_id_import_records"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_identifiers_provider_response_id_provider_responses"),
            type_="foreignkey",
        )
        batch_op.drop_column("provider_response_id")
        batch_op.drop_column("import_record_id")

    op.drop_table("work_series_claims")
    op.drop_table("work_concept_claims")
    op.drop_table("metadata_matches")
    with op.batch_alter_table("metadata_claims", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_metadata_claims_accepted_work_field",
            sqlite_where=sa.text("status = 'accepted' AND work_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_metadata_claims_accepted_edition_field",
            sqlite_where=sa.text("status = 'accepted' AND edition_id IS NOT NULL"),
        )

    op.drop_table("metadata_claims")
    op.drop_table("cover_candidates")
    with op.batch_alter_table("provider_responses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_responses_request_key"))

    op.drop_table("provider_responses")
    op.drop_table("enrichment_attempts")
    op.drop_table("series")
    op.drop_table("enrichment_runs")
    op.drop_table("concepts")
    # ### end Alembic commands ###
