"""add recommendation foundation

Revision ID: f0b0a91148f5
Revises: 61b4a8dca731
Create Date: 2026-08-21 11:27:57.028267
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f0b0a91148f5'
down_revision: str | Sequence[str] | None = '61b4a8dca731'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('usage_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name=op.f('ck_derivation_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_derivation_runs')),
    sa.UniqueConstraint('provider', 'model', 'purpose', 'input_hash', name=op.f('uq_derivation_runs_provider'))
    )
    op.create_table('taste_profile_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('source_work_count', sa.Integer(), nullable=False),
    sa.Column('represented_work_count', sa.Integer(), nullable=False),
    sa.Column('centroid_blob', sa.LargeBinary(), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name=op.f('ck_taste_profile_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taste_profile_runs')),
    sa.UniqueConstraint('algorithm_version', 'input_hash', name=op.f('uq_taste_profile_runs_algorithm_version'))
    )
    op.create_table('trait_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trait_definitions')),
    sa.UniqueConstraint('slug', name=op.f('uq_trait_definitions_slug'))
    )
    op.create_table('recommendation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_run_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('candidate_source', sa.String(length=100), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name=op.f('ck_recommendation_runs_status')),
    sa.ForeignKeyConstraint(['profile_run_id'], ['taste_profile_runs.id'], name=op.f('fk_recommendation_runs_profile_run_id_taste_profile_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_runs')),
    sa.UniqueConstraint('algorithm_version', 'input_hash', name=op.f('uq_recommendation_runs_algorithm_version'))
    )
    op.create_table('taste_profile_values',
    sa.Column('profile_run_id', sa.Integer(), nullable=False),
    sa.Column('signal_kind', sa.String(length=50), nullable=False),
    sa.Column('signal_key', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('representative_work_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['profile_run_id'], ['taste_profile_runs.id'], name=op.f('fk_taste_profile_values_profile_run_id_taste_profile_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_run_id', 'signal_kind', 'signal_key', name=op.f('pk_taste_profile_values'))
    )
    op.create_table('work_representations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('builder_version', sa.String(length=50), nullable=False),
    sa.Column('source_snapshot', sa.JSON(), nullable=False),
    sa.Column('derivation_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['derivation_run_id'], ['derivation_runs.id'], name=op.f('fk_work_representations_derivation_run_id_derivation_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name=op.f('fk_work_representations_work_id_works'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_representations')),
    sa.UniqueConstraint('work_id', 'kind', 'builder_version', 'input_hash', name=op.f('uq_work_representations_work_id'))
    )
    op.create_table('work_trait_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_reference', sa.JSON(), nullable=False),
    sa.Column('derivation_run_id', sa.Integer(), nullable=True),
    sa.Column('extractor_version', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_kind IN ('deterministic', 'provider', 'ai', 'manual')", name=op.f('ck_work_trait_values_source_kind')),
    sa.ForeignKeyConstraint(['derivation_run_id'], ['derivation_runs.id'], name=op.f('fk_work_trait_values_derivation_run_id_derivation_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trait_id'], ['trait_definitions.id'], name=op.f('fk_work_trait_values_trait_id_trait_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name=op.f('fk_work_trait_values_work_id_works'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_trait_values')),
    sa.UniqueConstraint('work_id', 'trait_id', 'source_kind', 'extractor_version', 'input_hash', name=op.f('uq_work_trait_values_work_id'))
    )
    op.create_table('recommendation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('reranked_score', sa.Float(), nullable=False),
    sa.Column('match_label', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(length=20), nullable=False),
    sa.Column('repetitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], name=op.f('fk_recommendation_items_run_id_recommendation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name=op.f('fk_recommendation_items_work_id_works'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_items')),
    sa.UniqueConstraint('run_id', 'work_id', name=op.f('uq_recommendation_items_run_id'))
    )
    op.create_table('work_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('representation_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('vector_blob', sa.LargeBinary(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('representation_version', sa.String(length=50), nullable=False),
    sa.Column('derivation_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['derivation_run_id'], ['derivation_runs.id'], name=op.f('fk_work_embeddings_derivation_run_id_derivation_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['representation_id'], ['work_representations.id'], name=op.f('fk_work_embeddings_representation_id_work_representations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name=op.f('fk_work_embeddings_work_id_works'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_embeddings')),
    sa.UniqueConstraint('work_id', 'purpose', 'provider', 'model', 'input_hash', name=op.f('uq_work_embeddings_work_id'))
    )
    op.create_table('recommendation_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_item_id', sa.Integer(), nullable=False),
    sa.Column('explanation_type', sa.String(length=50), nullable=False),
    sa.Column('structured_evidence', sa.JSON(), nullable=False),
    sa.Column('rendered_text', sa.String(), nullable=False),
    sa.Column('generator', sa.String(length=100), nullable=False),
    sa.Column('generator_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], name=op.f('fk_recommendation_explanations_recommendation_item_id_recommendation_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_explanations')),
    sa.UniqueConstraint('recommendation_item_id', name=op.f('uq_recommendation_explanations_recommendation_item_id'))
    )
    op.create_table('recommendation_neighbors',
    sa.Column('recommendation_item_id', sa.Integer(), nullable=False),
    sa.Column('read_work_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['read_work_id'], ['works.id'], name=op.f('fk_recommendation_neighbors_read_work_id_works'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], name=op.f('fk_recommendation_neighbors_recommendation_item_id_recommendation_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recommendation_item_id', 'read_work_id', name=op.f('pk_recommendation_neighbors'))
    )
    op.create_table('recommendation_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_item_id', sa.Integer(), nullable=False),
    sa.Column('signal_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], name=op.f('fk_recommendation_signals_recommendation_item_id_recommendation_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_signals')),
    sa.UniqueConstraint('recommendation_item_id', 'signal_name', name=op.f('uq_recommendation_signals_recommendation_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_signals')
    op.drop_table('recommendation_neighbors')
    op.drop_table('recommendation_explanations')
    op.drop_table('work_embeddings')
    op.drop_table('recommendation_items')
    op.drop_table('work_trait_values')
    op.drop_table('work_representations')
    op.drop_table('taste_profile_values')
    op.drop_table('recommendation_runs')
    op.drop_table('trait_definitions')
    op.drop_table('taste_profile_runs')
    op.drop_table('derivation_runs')
    # ### end Alembic commands ###
